### ISSUE TITLE
deprecated?

### ISSUE THREAD

**Issue by FraGoTe** [johntom/sails-firebirdsql#1]
Is it deprecated?,

I can find the package via npm.

**Comment by mariuz** [comment]
@FraGoTe you can use sails-firebirdsql https://github.com/ciferblat/sails-firebirdsql
git clone https://github.com/ciferblat/sails-firebirdsq
cd sails-firebirdsql/
npm install -g 

@johntom  can you remove the project also from github 
I found another project that seems with a lot more progress

**Comment by FraGoTe** [comment]
@mariuz  what is that project?
